import { defineCopy } from "@/lib/i18n/copy";
import type { Locale } from "@/lib/i18n/locale";
import { plural, type PluralForms } from "@/lib/i18n/plural";

/** „Została” / „zostały” / „zostało” po liczbie pozostałych rozmów lub minut. */
const REMAINING_VERB_PL: PluralForms = { one: "została", few: "zostały", many: "zostało" };

const ACCOUNT_PAGES_COPY = defineCopy(
  {
    security: {
      pageTitle: "Account - SafeSpace",
      passwordUpdated: "The password has been saved. You can sign in with e-mail and password or with Google.",
      back: "Back to the dashboard",
      title: "Account",
      signedInAs: "Signed in as",
      /** Nagłówek karty, gdy nie da się odczytać planu; zwykle kartę tytułuje nazwa planu. */
      planTitle: "Plan",
      planReadFailed:
        "We couldn't read the account plan. Refresh the page in a moment — the allowance details are also on the dashboard.",
      plan: {
        writtenLabel: "Written conversations",
        voiceTrialLabel: "Voice conversation",
        voicePoolLabel: "Voice conversations",
        upTo: (duration: string) => `up to ${duration}`,
        writtenRemaining: (remaining: number, limit: number) => `${remaining} of ${limit} left`,
        writtenUsedUp: (limit: number) => `${limit} of ${limit} used`,
        writtenUnlimited: "unlimited",
        voiceTrialAvailable: "1 trial",
        voiceTrialUsed: "trial used",
        voicePoolRemaining: (remaining: number, limit: number) => `${remaining} of ${limit} min left this month`,
        voicePoolReserved: (reserved: number) => `${reserved} min held by a conversation in progress`,
        voicePoolUsedUp: "this month's minutes are used up",
      },
      deletingNote: "Deleting a conversation doesn't return it to the allowance.",
      premiumMore: "The premium plan gives you more conversations.",
      premiumManual: "For now we grant it by hand — write to us.",
      writeAboutPremium: "Write to us about premium",
      passwordSummary: "Change password",
      passwordHint: "With a Google account, a password adds e‑mail sign-in.",
      appearanceTitle: "Language and appearance",
      appearanceNote: "The language applies on all your devices, the appearance only on this one.",
      dataTitle: "Your data",
      dataIntro: "You delete a conversation from its preview in the history.",
      privacyLink: "Privacy and terms",
      deleteAccount: "Delete account…",
      adminTitle: "Administration",
      adminIntro:
        "This account has access to aggregate statistics. The admin panel does not show conversation content.",
      openAdmin: "Open the admin panel",
      memory: {
        title: "Conversation memory",
        intro: "From your own words we note people and topics, separately for each perspective. Only you can see them.",
        modeOffIntro: "Currently unavailable. Cards saved earlier stay stored — you can delete them below.",
        peopleLabel: "People from conversations",
        peopleHint: "Who the people you mention are to you.",
        topicsLabel: "Topics from conversations",
        topicsHint: "What you struggle with, who it comes up with and how you cope.",
        switchNote:
          "Switching off stops saving and detaches the cards from conversations. Saved cards stay until you delete them; after switching back on, we note only new conversations.",
        viewLink: (firstName: string | null) => (firstName ? `See what ${firstName} remembers` : "See the saved cards"),
        deleteSummary: "Delete saved cards",
        deleteBody:
          "We delete the cards of every perspective and switch off saving what you delete. Conversation transcripts and summaries stay. This cannot be undone.",
        scopeLegend: "What to delete",
        scopePeople: "only people",
        scopeTopics: "only topics",
        scopeAll: "people and topics",
        deleteConfirmLabel: "I understand that the selected cards will be deleted permanently.",
        deleteSubmit: "Delete",
        status: {
          deleted_people: "All people cards have been deleted and remembering people is switched off.",
          deleted_topics: "All topics have been deleted and noting topics is switched off.",
          deleted_all: "People and topics have been deleted and both are switched off.",
          delete_failed: "The cards couldn't be deleted. Please try again in a moment.",
          delete_confirmation_required: "Tick the confirmation before deleting.",
          invalid_scope: "Choose what to delete.",
        },
      },
      peopleMemory: {
        readFailed: "We couldn't read this setting. Refresh the page in a moment.",
        toggleLegend: "Remember people from conversations",
        on: "On",
        off: "Off",
        status: {
          saved: "The setting has been saved.",
          save_failed: "The setting couldn't be saved. Please try again in a moment.",
          deleted: "All people cards have been deleted and remembering is switched off.",
          delete_failed: "The cards couldn't be deleted. Please try again in a moment.",
          delete_confirmation_required: "Tick the confirmation before deleting the cards.",
          unavailable: "Remembering people is currently unavailable, so it can't be switched on.",
        },
      },
      topicMap: {
        readFailed: "We couldn't read this setting. Refresh the page in a moment.",
        toggleLegend: "Note topics from conversations",
        on: "On",
        off: "Off",
        status: {
          saved: "The setting has been saved.",
          save_failed: "The setting couldn't be saved. Please try again in a moment.",
          deleted: "The topics have been deleted and switched off.",
          delete_failed: "The topics couldn't be deleted. Please try again in a moment.",
          delete_confirmation_required: "Tick the confirmation before deleting the topics.",
          unavailable: "Topics from conversations are currently unavailable, so they can't be switched on.",
        },
      },
    },
    delete: {
      pageTitle: "Delete account - SafeSpace",
      title: "Delete account",
      introBefore: "You are deleting the account",
      introAfter: ". This action is permanent and cannot be undone.",
      consequences: [
        "We'll delete all your conversations, messages, summaries and avatar memory.",
        "We'll delete your profile and chosen avatar. You'll also lose access to the current account plan.",
        "Ongoing conversations will be interrupted and the account will be signed out on all devices.",
      ] as readonly string[],
      confirmLabel: (word: string) => `To confirm, type ${word}`,
      cancel: "Cancel",
      submit: "Delete the account permanently",
    },
    blocked: {
      pageTitle: "Account unavailable - SafeSpace",
      eyebrow: "SafeSpace",
      title: "The account is temporarily unavailable",
      unavailableBody:
        "We can't confirm access to the private part of the product right now. Try again later or sign out.",
      blockedBody:
        "Access to the private part of SafeSpace has been blocked for this account. You can sign out and contact SafeSpace support.",
      privacyNote: "For privacy reasons this page shows no account details or the reason for the decision.",
      contactPrefix: "Contact support:",
      contactSuffix: ". Write from your account's e‑mail address — do not include conversation content.",
      signOut: "Sign out",
      backHome: "Back to the home page",
      deleteAccount: "Delete the account and your data",
    },
  },
  {
    security: {
      pageTitle: "Konto - SafeSpace",
      passwordUpdated: "Hasło zostało zapisane. Możesz logować się e-mailem i hasłem albo przez Google.",
      back: "Wróć do panelu",
      title: "Konto",
      signedInAs: "Zalogowano jako",
      planTitle: "Plan",
      planReadFailed:
        "Nie udało się odczytać planu konta. Odśwież stronę za chwilę — szczegóły puli rozmów zobaczysz też w panelu.",
      plan: {
        writtenLabel: "Rozmowy pisane",
        voiceTrialLabel: "Rozmowa głosowa",
        voicePoolLabel: "Rozmowy głosowe",
        upTo: (duration) => `do ${duration}`,
        // Czasownik zgadza się z liczbą: „1 z 3 została”, „2 z 3 zostały”, „5 z 8 zostało”.
        writtenRemaining: (remaining, limit) => `${remaining} z ${limit} ${plural("pl", remaining, REMAINING_VERB_PL)}`,
        writtenUsedUp: (limit) => `wykorzystano ${limit} z ${limit}`,
        writtenUnlimited: "bez limitu",
        voiceTrialAvailable: "1 próba",
        voiceTrialUsed: "próba wykorzystana",
        voicePoolRemaining: (remaining, limit) =>
          `${remaining} z ${limit} min ${plural("pl", remaining, REMAINING_VERB_PL)} w tym miesiącu`,
        voicePoolReserved: (reserved) => `${reserved} min rezerwuje trwająca rozmowa`,
        voicePoolUsedUp: "pula na ten miesiąc wykorzystana",
      },
      deletingNote: "Usunięcie rozmowy nie zwraca jej do puli.",
      premiumMore: "Więcej rozmów daje plan premium.",
      premiumManual: "Na razie przyznajemy go ręcznie — napisz do nas.",
      writeAboutPremium: "Napisz w sprawie premium",
      passwordSummary: "Zmień hasło",
      passwordHint: "Przy koncie z Google hasło doda logowanie e‑mailem.",
      appearanceTitle: "Język i wygląd",
      appearanceNote: "Język obowiązuje na wszystkich Twoich urządzeniach, wygląd — tylko na tym.",
      dataTitle: "Twoje dane",
      dataIntro: "Rozmowę usuniesz z jej podglądu w historii.",
      privacyLink: "Prywatność i zasady",
      deleteAccount: "Usuń konto…",
      adminTitle: "Administracja",
      adminIntro: "To konto ma dostęp do statystyk zbiorczych. Panel administracyjny nie pokazuje treści rozmów.",
      openAdmin: "Otwórz panel administracyjny",
      memory: {
        title: "Pamięć rozmów",
        intro: "Z Twoich słów zapisujemy osoby i tematy, osobno dla każdej perspektywy. Widzisz je tylko Ty.",
        modeOffIntro: "Teraz niedostępne. Zapisane wcześniej karty wciąż są przechowywane — możesz je usunąć poniżej.",
        peopleLabel: "Osoby z rozmów",
        peopleHint: "Kim są dla Ciebie ludzie, o których mówisz.",
        topicsLabel: "Tematy z rozmów",
        topicsHint: "Z czym się mierzysz, przy kim to wraca i jak sobie radzisz.",
        switchNote:
          "Wyłączenie zatrzymuje zapisywanie i odłącza karty od rozmów. Zapisane karty zostają, dopóki ich nie usuniesz; po ponownym włączeniu zapisujemy tylko nowe rozmowy.",
        viewLink: (firstName) => (firstName ? `Zobacz, co pamięta ${firstName}` : "Zobacz zapisane karty"),
        deleteSummary: "Usuń zapisane karty",
        deleteBody:
          "Usuwamy karty wszystkich perspektyw i wyłączamy zapisywanie tego, co usuwasz. Zapisy rozmów i podsumowania zostają. Tej operacji nie można cofnąć.",
        scopeLegend: "Co usunąć",
        scopePeople: "tylko osoby",
        scopeTopics: "tylko tematy",
        scopeAll: "osoby i tematy",
        deleteConfirmLabel: "Rozumiem, że wybrane karty zostaną trwale usunięte.",
        deleteSubmit: "Usuń",
        status: {
          deleted_people: "Wszystkie karty osób zostały usunięte, a zapamiętywanie osób wyłączone.",
          deleted_topics: "Wszystkie tematy zostały usunięte, a zapisywanie tematów wyłączone.",
          deleted_all: "Osoby i tematy zostały usunięte, a zapisywanie obu wyłączone.",
          delete_failed: "Nie udało się usunąć kart. Spróbuj ponownie za chwilę.",
          delete_confirmation_required: "Zaznacz potwierdzenie, zanim usuniesz.",
          invalid_scope: "Wybierz, co usunąć.",
        },
      },
      peopleMemory: {
        readFailed: "Nie udało się odczytać tego ustawienia. Odśwież stronę za chwilę.",
        toggleLegend: "Zapamiętuj osoby z rozmów",
        on: "Włączone",
        off: "Wyłączone",
        status: {
          saved: "Ustawienie zostało zapisane.",
          save_failed: "Nie udało się zapisać ustawienia. Spróbuj ponownie za chwilę.",
          deleted: "Wszystkie karty osób zostały usunięte, a zapamiętywanie wyłączone.",
          delete_failed: "Nie udało się usunąć kart. Spróbuj ponownie za chwilę.",
          delete_confirmation_required: "Zaznacz potwierdzenie, zanim usuniesz karty.",
          unavailable: "Zapamiętywanie osób jest obecnie niedostępne, więc nie da się go włączyć.",
        },
      },
      topicMap: {
        readFailed: "Nie udało się odczytać tego ustawienia. Odśwież stronę za chwilę.",
        toggleLegend: "Zapisuj tematy z rozmów",
        on: "Włączone",
        off: "Wyłączone",
        status: {
          saved: "Ustawienie zostało zapisane.",
          save_failed: "Nie udało się zapisać ustawienia. Spróbuj ponownie za chwilę.",
          deleted: "Tematy zostały usunięte i wyłączone.",
          delete_failed: "Nie udało się usunąć tematów. Spróbuj ponownie za chwilę.",
          delete_confirmation_required: "Zaznacz potwierdzenie, zanim usuniesz tematy.",
          unavailable: "Zapisywanie tematów jest obecnie niedostępne, więc nie da się go włączyć.",
        },
      },
    },
    delete: {
      pageTitle: "Usuń konto - SafeSpace",
      title: "Usuń konto",
      introBefore: "Usuwasz konto",
      introAfter: ". Ta operacja jest trwała i nie można jej cofnąć.",
      consequences: [
        "Usuniemy wszystkie Twoje rozmowy, wiadomości, podsumowania i pamięć awatarów.",
        "Usuniemy profil i wybranego awatara. Utracisz też dostęp do obecnego planu konta.",
        "Trwające rozmowy zostaną przerwane, a konto zostanie wylogowane na wszystkich urządzeniach.",
      ],
      confirmLabel: (word) => `Aby potwierdzić, wpisz ${word}`,
      cancel: "Anuluj",
      submit: "Usuń konto bezpowrotnie",
    },
    blocked: {
      pageTitle: "Konto niedostępne - SafeSpace",
      eyebrow: "SafeSpace",
      title: "Konto jest chwilowo niedostępne",
      unavailableBody:
        "Nie możemy teraz potwierdzić dostępu do prywatnej części produktu. Spróbuj ponownie później albo wyloguj się.",
      blockedBody:
        "Dostęp do prywatnej części SafeSpace został zablokowany dla tego konta. Możesz się wylogować i skontaktować z obsługą SafeSpace.",
      privacyNote: "Ze względów prywatności ta strona nie pokazuje szczegółów konta ani powodu decyzji.",
      contactPrefix: "Kontakt z obsługą:",
      contactSuffix: ". Napisz z adresu e‑mail swojego konta — nie podawaj treści rozmów.",
      signOut: "Wyloguj się",
      backHome: "Wróć na stronę główną",
      deleteAccount: "Usuń konto i swoje dane",
    },
  },
);

export function getAccountPagesCopy(locale: Locale) {
  return ACCOUNT_PAGES_COPY[locale];
}
