import { env } from "cloudflare:workers";
import { defineMiddleware } from "astro:middleware";
import { readAccountAccessState } from "@/lib/admin/account-access";
import { AUTHENTICATED_REDIRECT_PATH } from "@/lib/auth-redirect";
import { logOperationalEvent } from "@/lib/operational-visibility/logger";
import {
  createOperationalRequestId,
  withOperationalRequestIdHeader,
} from "@/lib/operational-visibility/request-context";
import type { OperationalEventLevel, OperationalReasonCode } from "@/lib/operational-visibility/types";
import {
  checkAuthRateLimit,
  checkSessionRateLimit,
  getAuthRateLimitRedirect,
  getRateLimitKey,
  isAuthRateLimitedRequest,
  isRateLimitedApiRequest,
} from "@/lib/rate-limit";
import { ACCOUNT_ACCESS_UNAVAILABLE_PATH, BLOCKED_ACCOUNT_PATH, evaluateApiBodyGuard } from "@/lib/request-guards";
import { createClient } from "@/lib/supabase";

const PROTECTED_ROUTES = [AUTHENTICATED_REDIRECT_PATH, "/account", "/admin"] as const;

// Baseline browser hardening for every response. CSP is generated by Astro from
// the actual island/style hashes (see astro.config.mjs).
const SECURITY_HEADERS: Record<string, string> = {
  "X-Frame-Options": "DENY",
  "X-Content-Type-Options": "nosniff",
  "Referrer-Policy": "strict-origin-when-cross-origin",
  "Strict-Transport-Security": "max-age=31536000; includeSubDomains",
  "Permissions-Policy": "camera=(), microphone=(self), geolocation=()",
};

function isPrivateResponsePath(pathname: string) {
  return pathname.startsWith("/api/") || pathname.startsWith("/auth/") || isProtectedRoute(pathname);
}

function withSecurityHeaders(response: Response, pathname: string) {
  for (const [name, value] of Object.entries(SECURITY_HEADERS)) {
    response.headers.set(name, value);
  }

  if (isPrivateResponsePath(pathname)) {
    response.headers.set("Cache-Control", "private, no-store, max-age=0");
    response.headers.set("Pragma", "no-cache");
    response.headers.set("Expires", "0");
  }

  return response;
}

function isProtectedRoute(pathname: string) {
  return PROTECTED_ROUTES.some((route) => pathname === route || pathname.startsWith(`${route}/`));
}

function getProtectedRouteBucket(pathname: string) {
  return PROTECTED_ROUTES.find((route) => pathname === route || pathname.startsWith(`${route}/`));
}

function shouldCheckAccountAccess(pathname: string) {
  return isProtectedRoute(pathname) && pathname !== BLOCKED_ACCOUNT_PATH && pathname !== "/account/delete";
}

export const onRequest = defineMiddleware(async (context, next) => {
  const requestId = createOperationalRequestId();
  context.locals.requestId = requestId;

  const { pathname } = context.url;
  const { method } = context.request;

  function finalize(response: Response) {
    return withSecurityHeaders(withOperationalRequestIdHeader(response, requestId), pathname);
  }

  function logRequestRejected(
    status: number,
    reasonCode: OperationalReasonCode,
    level: OperationalEventLevel = "warn",
  ) {
    logOperationalEvent(
      {
        event: "route.request_rejected",
        level,
        route: pathname,
        method,
        outcome: "blocked",
        status,
        reasonCode,
      },
      { requestId },
    );
  }

  function rejectJson(status: number, code: OperationalReasonCode, headers?: HeadersInit) {
    return finalize(Response.json({ ok: false, code }, { status, headers }));
  }

  const bodyGuard = evaluateApiBodyGuard(context.request, pathname);

  if (!bodyGuard.ok) {
    logRequestRejected(bodyGuard.status, bodyGuard.reasonCode);
    return rejectJson(bodyGuard.status, bodyGuard.reasonCode);
  }

  // Credential-handling auth forms are throttled per client IP before the
  // Supabase round-trip, so a credential-stuffing burst costs no auth calls.
  // Fail-open by design (see `rate-limit.ts`): the verdict is only ever
  // "allowed" or "limited". An over-limit form POST is redirected back to its
  // page with the `rate_limited` copy — these routes speak redirects, not JSON.
  const authRateLimitRedirect = isAuthRateLimitedRequest(method, pathname) ? getAuthRateLimitRedirect(pathname) : null;

  if (authRateLimitRedirect) {
    const verdict = await checkAuthRateLimit(env.AUTH_RATE_LIMITER, getRateLimitKey(null, context.request));

    if (verdict === "limited") {
      logRequestRejected(303, "rate_limited");
      return finalize(context.redirect(authRateLimitRedirect, 303));
    }
  }

  const supabase = createClient(context.request.headers, context.cookies);

  if (supabase) {
    const {
      data: { user },
    } = await supabase.auth.getUser();
    context.locals.user = user ?? null;
  } else {
    context.locals.user = null;
  }
  context.locals.accountAccess = null;

  if (isRateLimitedApiRequest(method, pathname)) {
    const limiter = env.SESSION_RATE_LIMITER;
    const key = getRateLimitKey(context.locals.user?.id ?? null, context.request);
    const verdict = await checkSessionRateLimit(limiter, key, { failClosed: import.meta.env.PROD });

    if (verdict === "limited") {
      logRequestRejected(429, "rate_limited");
      return rejectJson(429, "rate_limited", { "Retry-After": "60" });
    }

    if (verdict === "unavailable") {
      logRequestRejected(503, "rate_limiter_unavailable", "error");
      return rejectJson(503, "rate_limiter_unavailable");
    }
  }

  if (isProtectedRoute(pathname)) {
    if (!context.locals.user) {
      logOperationalEvent(
        {
          event: "route.protected_redirect",
          level: "warn",
          route: getProtectedRouteBucket(pathname),
          method,
          outcome: "redirected",
          status: 302,
          reasonCode: "missing_auth",
        },
        { requestId },
      );

      return finalize(context.redirect("/auth/signin"));
    }

    if (shouldCheckAccountAccess(pathname)) {
      const accountAccess = await readAccountAccessState(context, supabase);

      if (!accountAccess.ok) {
        logOperationalEvent(
          {
            event: "route.protected_redirect",
            level: "warn",
            route: getProtectedRouteBucket(pathname),
            method,
            outcome: "redirected",
            status: 302,
            reasonCode: accountAccess.error.code,
          },
          { requestId },
        );

        return finalize(context.redirect(ACCOUNT_ACCESS_UNAVAILABLE_PATH));
      }

      context.locals.accountAccess = accountAccess.data;

      if (accountAccess.data.status === "blocked") {
        logOperationalEvent(
          {
            event: "route.protected_redirect",
            level: "warn",
            route: getProtectedRouteBucket(pathname),
            method,
            outcome: "redirected",
            status: 302,
            reasonCode: "account_blocked",
          },
          { requestId },
        );

        return finalize(context.redirect(BLOCKED_ACCOUNT_PATH));
      }
    }
  }

  const response = await next();
  return finalize(response);
});
